"""
Train LSTM on historical soil readings from soil_data.db.
This script extracts the time-series data generated by `generate_lstm_data.py`,
transforms it into overlapping sequences (sliding windows), and trains a Multi-Output LSTM.
The model predicts both the Fertilizer Type (Classification) and Amount (Regression).

Produces:
  - models/lstm_fertilizer.keras (The trained neural network)
  - models/lstm_scaler.pkl (MinMaxScaler for normalizing input features)
  - models/lstm_label_encoder.pkl (LabelEncoder for translating string classes to integers)
"""
import sqlite3
import numpy as np
import joblib
import os
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, mean_absolute_error

DB_PATH = "soil_data.db"
MODEL_DIR = "models"
# Number of consecutive readings the LSTM will look at to make a single prediction
SEQ_LENGTH = 15
# The input features required by the model
FEATURES = ["nitrogen", "phosphorus", "potassium", "ph", "moisture", "temperature", "ec"]
EPOCHS = 100
BATCH_SIZE = 32


def load_data():
    """
    Connects to the SQLite database and retrieves all soil readings,
    ordered chronologically by ID to maintain the time-series integrity.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("SELECT * FROM soil_readings ORDER BY id ASC")
    rows = [dict(r) for r in cur.fetchall()]
    cur.close()
    conn.close()
    print(f"[INFO] Loaded {len(rows)} rows")
    return rows


def create_sequences(rows, scaler, label_encoder):
    """
    Transforms the flat dataset into 3D overlapping sequences required by the LSTM.
    Shape transformation: (Num_Samples, Features) -> (Num_Sequences, Sequence_Length, Features)
    
    Args:
        rows: List of dictionary rows from the database.
        scaler: Scikit-learn scaler to normalize feature data.
        label_encoder: Scikit-learn encoder to convert string targets to integers.
    """
    # Extract features and targets into separate arrays
    feature_matrix = np.array([[r[f] for f in FEATURES] for r in rows], dtype=np.float32)
    fert_types = [r["fertilizer_type"] for r in rows]
    amounts = np.array([r["fertilizer_amount"] for r in rows], dtype=np.float32)

    # Normalize the features so the neural network converges faster and more reliably.
    # We fit on ALL data here because it's a synthetic dataset generated specifically for training.
    scaled = scaler.fit_transform(feature_matrix)
    encoded = label_encoder.fit_transform(fert_types)

    X, y_type, y_amount = [], [], []

    # Slide a window of size SEQ_LENGTH over the data.
    # E.g., if SEQ=15, X will contain rows [0..14], and Y will be the target for row [15].
    for i in range(len(scaled) - SEQ_LENGTH):
        X.append(scaled[i : i + SEQ_LENGTH])
        y_type.append(encoded[i + SEQ_LENGTH])
        y_amount.append(amounts[i + SEQ_LENGTH])

    return np.array(X), np.array(y_type), np.array(y_amount)


def build_model(seq_length, n_features, n_classes):
    """
    Constructs the Multi-Output LSTM architecture.
    
    The model has a shared LSTM base to understand the temporal soil patterns,
    which then splits into two specialized heads:
    1. A Classification Head (softmax) for picking the fertilizer type.
    2. A Regression Head (linear) for predicting the exact amount in kg/ha.
    """
    import tensorflow as tf
    from tensorflow.keras import layers, Model, regularizers

    # Input layer expecting a 3D tensor: (Batch, Sequence_Length, Features)
    inputs = layers.Input(shape=(seq_length, n_features), name="soil_seq")

    # --- Shared Temporal Base ---
    # First LSTM layer: Captures primary temporal relationships.
    # L2 Regularization penalizes large weights to prevent overfitting the synthetic data.
    x = layers.LSTM(128, return_sequences=True, 
                    kernel_regularizer=regularizers.l2(0.001),
                    name="lstm_1")(inputs)
    x = layers.BatchNormalization()(x) # Stabilizes training
    x = layers.Dropout(0.2)(x) # Randomly drops 20% of connections to prevent over-reliance on specific nodes
    
    # Second LSTM layer: Condenses the sequence down to a single feature vector representing the entire 15-step history.
    x = layers.LSTM(128, 
                    kernel_regularizer=regularizers.l2(0.001),
                    name="lstm_2")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.2)(x)

    # Dense shared layer to process the final temporal features before splitting
    shared = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(0.001))(x)
    shared = layers.Dropout(0.2)(shared)

    # --- Head 1: Fertilizer Type (Classification) ---
    type_out = layers.Dense(32, activation="relu")(shared)
    # Output layer with softmax to output probabilities for each fertilizer class
    type_out = layers.Dense(n_classes, activation="softmax", name="fert_type")(type_out)

    # --- Head 2: Fertilizer Amount (Regression) ---
    amt_out = layers.Dense(32, activation="relu")(shared)
    # Linear output layer to predict a continuous value
    amt_out = layers.Dense(1, activation="linear", name="fert_amount")(amt_out)

    # Combine into a single model
    model = Model(inputs=inputs, outputs=[type_out, amt_out])
    
    # Compile the model with multiple losses.
    # We weight the classification loss heavier (1.0) than the regression loss (0.01) 
    # because getting the correct fertilizer TYPE is more critical than the exact amount.
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss={"fert_type": "sparse_categorical_crossentropy", "fert_amount": "huber"},
        loss_weights={"fert_type": 1.0, "fert_amount": 0.01},
        metrics={"fert_type": ["accuracy"], "fert_amount": ["mae"]},
    )
    return model


def main():
    """
    Main training execution pipeline.
    """
    # Suppress TensorFlow logging warnings
    os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
    os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
    import tensorflow as tf

    print("=" * 60)
    print("  LSTM Fertilizer Model Training")
    print("=" * 60)

    # 1. Load and prepare data
    rows = load_data()
    scaler = MinMaxScaler()
    label_encoder = LabelEncoder()

    X, y_type, y_amount = create_sequences(rows, scaler, label_encoder)
    print(f"[INFO] Sequences: {len(X)}, Shape: {X.shape}")
    print(f"[INFO] Classes: {list(label_encoder.classes_)}")

    # Display dataset balance
    unique, counts = np.unique(y_type, return_counts=True)
    for u, c in zip(unique, counts):
        print(f"   {label_encoder.inverse_transform([u])[0]:15s} -> {c} samples")

    # 2. Split into Training (80%) and Validation/Testing (20%) sets.
    # Stratify ensures the ratio of fertilizer classes remains consistent in both splits.
    X_train, X_test, yt_train, yt_test, ya_train, ya_test = train_test_split(
        X, y_type, y_amount, test_size=0.2, random_state=42, stratify=y_type
    )
    print(f"[INFO] Train: {len(X_train)}, Test: {len(X_test)}")

    # 3. Build Model
    model = build_model(SEQ_LENGTH, len(FEATURES), len(label_encoder.classes_))
    model.summary()

    print(f"\n[INFO] Training for up to {EPOCHS} epochs...")
    
    # 4. Train the Model
    history = model.fit(
        X_train,
        {"fert_type": yt_train, "fert_amount": ya_train}, # Multiple targets
        validation_data=(X_test, {"fert_type": yt_test, "fert_amount": ya_test}),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        verbose=1,
        callbacks=[
            # EarlyStopping prevents overtraining by stopping if validation accuracy doesn't improve for 20 epochs
            tf.keras.callbacks.EarlyStopping(
                monitor="val_fert_type_accuracy", patience=20,
                restore_best_weights=True, mode="max",
            ),
            # ReduceLROnPlateau drops the learning rate when the loss plateaus, helping the model "fine-tune"
            tf.keras.callbacks.ReduceLROnPlateau(
                monitor="val_loss", factor=0.5, patience=5, verbose=1
            ),
        ],
    )

    # 5. Evaluate the final model on the test set
    print("\n" + "=" * 60)
    print("  Evaluation Results")
    print("=" * 60)

    preds = model.predict(X_test)
    # Convert softmax probabilities back to class indices
    type_pred_classes = np.argmax(preds[0], axis=1)
    amount_preds = preds[1].flatten()

    print("\nFertilizer Type Classification:")
    print(classification_report(
        yt_test, type_pred_classes, target_names=label_encoder.classes_
    ))

    mae = mean_absolute_error(ya_test, amount_preds)
    print(f"Amount MAE: {mae:.2f} kg/ha")

    # 6. Save the Model and preprocessors for use in app.py
    model.save(os.path.join(MODEL_DIR, "lstm_fertilizer.keras"))
    joblib.dump(scaler, os.path.join(MODEL_DIR, "lstm_scaler.pkl"))
    joblib.dump(label_encoder, os.path.join(MODEL_DIR, "lstm_label_encoder.pkl"))

    val_acc = max(history.history.get("val_fert_type_accuracy", [0]))
    print(f"\n[RESULT] Best val accuracy: {val_acc * 100:.1f}%")
    print(f"[RESULT] Amount MAE: {mae:.2f} kg/ha")
    print("[OK] All files saved to models/")


if __name__ == "__main__":
    main()
